# spring.application.name=jpa

server:
  port: 8181

spring:
  application:
    name: todo
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB # 1개 파일의 최대 사이즈
      max-request-size: 20MB # 전체 요청의 최대 사이즈

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html

jwt:
  secret: g7AzFEIVIjIyK3cDe7AQziOGx2wdOvZkeZQmnsJh1BRDSKpvYjvkvy8GypEoe34pGxYyGI7pSrIQHv0YGtt32Q==

#upload file path
upload:
  path: C:/todo_upload

#kakao login setting
kakao:
  client_id: 5ab78d74ee74e37fb51f73034378377b
  redirect_url: http://localhost:3000/oauth/kakao
  client_secret: E3aiP1Yza0r2W66l3s2LuDT4gcAW3Etu
